export default function useCountry() {

    function getCountries() {
        return {
            US: 'United States of America (USA)',
            CA: 'Canada',
            GB: 'Great Britain',
            AD: 'Andorra',
            AE: 'United Arab Emirates',
            AF: 'Afghanistan',
            AG: 'Barbuda',
            AI: 'Anguilla',
            AL: 'Albania',
            AM: 'Armenia',
            AO: 'Angola',
            AR: 'Argentina',
            AS: 'American Samoa',
            AT: 'Austria',
            AU: 'Australia',
            AW: 'Aruba',
            AZ: 'Azerbaijan',
            BA: 'Bosnia-Herzegovina',
            BB: 'Barbados',
            BD: 'Bangladesh',
            BE: 'Belgium',
            BF: 'Burkina Faso',
            BG: 'Bulgaria',
            BH: 'Bahrain',
            BI: 'Burundi',
            BJ: 'Benin',
            BM: 'Bermuda',
            BN: 'Brunei',
            BO: 'Bolivia',
            BQ: 'St. Eustatius',
            BR: 'Brazil',
            BS: 'Bahamas',
            BT: 'Bhutan',
            BW: 'Botswana',
            BY: 'Belarus',
            BZ: 'Belize',
            CD: 'Congo, Dem. Rep. of',
            CG: 'Congo',
            CH: 'Switzerland',
            CI: 'Ivory Coast',
            CK: 'Cook Islands',
            CL: 'Chile',
            CM: 'Cameroon',
            CN: 'China',
            CO: 'Colombia',
            CR: 'Costa Rica',
            CS: 'Serbia and Montenegro',
            CV: 'Cape Verde',
            CW: 'Curacao',
            CY: 'Cyprus',
            CZ: 'Czech Republic',
            DE: 'Germany',
            DJ: 'Djibouti',
            DK: 'Denmark',
            DM: 'Dominica',
            DO: 'Dominican Republic',
            DZ: 'Algeria',
            EC: 'Ecuador',
            EE: 'Estonia',
            EG: 'Egypt',
            ER: 'Eritrea',
            ES: 'Spain',
            ET: 'Ethiopia',
            FI: 'Finland',
            FJ: 'Fiji',
            FM: 'Micronesia',
            FO: 'Faeroe Islands',
            FR: 'France',
            GA: 'Gabon',
            GD: 'Grenada',
            GE: 'Georgia, Republic of',
            GF: 'French Guiana',
            GH: 'Ghana',
            GI: 'Gibraltar',
            GL: 'Greenland',
            GM: 'Gambia',
            GN: 'Guinea',
            GP: 'St. Barthelemy',
            GR: 'Greece',
            GT: 'Guatemala',
            GU: 'Guam',
            GY: 'Guyana',
            HK: 'Hong Kong',
            HN: 'Honduras',
            HR: 'Croatia',
            HT: 'Haiti',
            HU: 'Hungary',
            ID: 'Indonesia',
            IE: 'Ireland, Republic of',
            IL: 'Israel',
            IN: 'India',
            IQ: 'Iraq',
            IS: 'Iceland',
            IT: 'Vatican',
            JM: 'Jamaica',
            JO: 'Jordan',
            JP: 'Japan',
            KE: 'Kenya',
            KG: 'Kyrgyzstan',
            KH: 'Cambodia',
            KN: 'St. Kitts and Nevis',
            KR: 'Korea, South',
            KW: 'Kuwait',
            KY: 'Cayman Islands',
            KZ: 'Kazakhstan',
            LA: 'Laos',
            LB: 'Lebanon',
            LC: 'St. Lucia',
            LI: 'Liechtenstein',
            LK: 'Sri Lanka',
            LR: 'Liberia',
            LS: 'Lesotho',
            LT: 'Lithuania',
            LU: 'Luxembourg',
            LV: 'Latvia',
            LY: 'Libya',
            MA: 'Morocco',
            MC: 'Monaco',
            MD: 'Moldova',
            MF: 'St. Martin',
            MG: 'Madagascar',
            MH: 'Marshall Islands',
            MK: 'Macedonia',
            ML: 'Mali',
            MN: 'Mongolia',
            MO: 'Macau',
            MP: 'Saipan',
            MQ: 'Martinique',
            MR: 'Mauritania',
            MS: 'Montserrat',
            MT: 'Malta',
            MU: 'Mauritius',
            MV: 'Maldives, Republic of',
            MW: 'Malawi',
            MX: 'Mexico',
            MY: 'Malaysia',
            MZ: 'Mozambique',
            NA: 'Namibia',
            NC: 'New Caledonia',
            NE: 'Niger',
            NG: 'Nigeria',
            NI: 'Nicaragua',
            NL: 'Netherlands',
            NO: 'Norway',
            NP: 'Nepal',
            NZ: 'New Zealand',
            OM: 'Oman',
            PA: 'Panama',
            PE: 'Peru',
            PF: 'French Polynesia',
            PG: 'Papua New Guinea',
            PH: 'Philippines',
            PK: 'Pakistan',
            PL: 'Poland',
            PR: 'Puerto Rico',
            PS: 'Palestine',
            PT: 'Portugal',
            PW: 'Palau',
            PY: 'Paraguay',
            QA: 'Qatar',
            RE: 'Reunion',
            RO: 'Romania',
            RU: 'Russia',
            RW: 'Rwanda',
            SA: 'Saudi Arabia',
            SC: 'Seychelles',
            SE: 'Sweden',
            SG: 'Singapore',
            SI: 'Slovenia',
            SK: 'Slovak Republic',
            SN: 'Senegal',
            SR: 'Suriname',
            SV: 'El Salvador',
            SX: 'St. Maarten​',
            SY: 'Syria',
            SZ: 'Swaziland',
            TC: 'Turks and Caicos Islands',
            TD: 'Chad',
            TG: 'Togo',
            TH: 'Thailand',
            TL: 'East Timor',
            TN: 'Tunisia',
            TO: 'Tonga',
            TR: 'Turkey',
            TT: 'Trinidad and Tobago',
            TW: 'Taiwan',
            TZ: 'Tanzania',
            UA: 'Ukraine',
            UG: 'Uganda',
            UY: 'Uruguay',
            UZ: 'Uzbekistan',
            VC: 'St. Vincent',
            VE: 'Venezuela',
            VG: 'British Virgin Islands',
            VI: 'U.S. Virgin Islands',
            VN: 'Vietnam',
            VU: 'Vanuatu',
            WF: 'Wallis & Futuna Islands',
            WS: 'Samoa',
            YE: 'Yemen, The Republic of',
            ZA: 'South African Republic',
            ZM: 'Zambia',
            ZW: 'Zimbabwe'
        }
    }

    // https://www.dnbcf.com/utilities/list-country-currency-code
    function getCountryCodeToCurrencyCodeMap() {
        return {
            AD: 'EUR',
            AE: 'AED',
            AF: 'AFN',
            AG: 'XCD',
            AI: 'XCD',
            AL: 'ALL',
            AM: 'AMD',
            AN: 'ANG',
            AO: 'AOA',
            AQ: 'AQD',
            AR: 'ARS',
            AS: 'EUR',
            AT: 'EUR',
            AU: 'AUD',
            AW: 'ANG',
            AX: 'EUR',
            AZ: 'AZN',
            BA: 'BAM',
            BB: 'BBD',
            BD: 'BDT',
            BE: 'EUR',
            BF: 'XOF',
            BG: 'BGN',
            BH: 'BHD',
            BI: 'BIF',
            BJ: 'XOF',
            BL: 'EUR',
            BM: 'BMD',
            BN: 'BND',
            BO: 'BOB',
            BR: 'BRL',
            BS: 'BSD',
            BT: 'INR',
            BV: 'NOK',
            BW: 'BWP',
            BY: 'BYR',
            BZ: 'BZD',
            CA: 'CAD',
            CC: 'AUD',
            CD: 'CDF',
            CF: 'XAF',
            CG: 'XAF',
            CH: 'CHF',
            CI: 'XOF',
            CK: 'NZD',
            CL: 'CLP',
            CM: 'XAF',
            CN: 'CNY',
            CO: 'COP',
            CR: 'CRC',
            CU: 'CUP',
            CV: 'CVE',
            CX: 'AUD',
            CY: 'CYP',
            CZ: 'CZK',
            DE: 'EUR',
            DJ: 'DJF',
            DK: 'DKK',
            DM: 'XCD',
            DO: 'DOP',
            DZ: 'DZD',
            EC: 'ECS',
            EE: 'EEK',
            EG: 'EGP',
            EH: 'MAD',
            ER: 'ETB',
            ES: 'EUR',
            ET: 'ETB',
            FI: 'EUR',
            FJ: 'FJD',
            FK: 'FKP',
            FM: 'USD',
            FO: 'DKK',
            FR: 'EUR',
            GA: 'XAF',
            GB: 'GBP',
            GD: 'XCD',
            GE: 'GEL',
            GF: 'EUR',
            GG: 'GGP',
            GH: 'GHS',
            GI: 'GIP',
            GL: 'DKK',
            GM: 'GMD',
            GN: 'GNF',
            GP: 'EUR',
            GQ: 'XAF',
            GR: 'EUR',
            GS: 'GBP',
            GT: 'GTQ',
            GU: 'USD',
            GW: 'XOF',
            GY: 'GYD',
            HK: 'HKD',
            HM: 'AUD',
            HN: 'HNL',
            HR: 'HRK',
            HT: 'HTG',
            HU: 'HUF',
            ID: 'IDR',
            IE: 'EUR',
            IL: 'ILS',
            IM: 'GBP',
            IN: 'INR',
            IO: 'USD',
            IQ: 'IQD',
            IR: 'IRR',
            IS: 'ISK',
            IT: 'EUR',
            JE: 'GBP',
            JM: 'JMD',
            JO: 'JOD',
            JP: 'JPY',
            KE: 'KES',
            KG: 'KGS',
            KH: 'KHR',
            KI: 'AUD',
            KM: 'KMF',
            KN: 'XCD',
            KP: 'KPW',
            KR: 'KRW',
            KW: 'KWD',
            KY: 'KYD',
            KZ: 'KZT',
            LA: 'LAK',
            LB: 'LBP',
            LC: 'XCD',
            LI: 'CHF',
            LK: 'LKR',
            LR: 'LRD',
            LS: 'LSL',
            LT: 'LTL',
            LU: 'EUR',
            LV: 'LVL',
            LY: 'LYD',
            MA: 'MAD',
            MC: 'EUR',
            MD: 'MDL',
            ME: 'EUR',
            MF: 'ANG',
            MG: 'MGA',
            MH: 'USD',
            MK: 'MKD',
            ML: 'XOF',
            MM: 'MMK',
            MN: 'MNT',
            MO: 'MOP',
            MP: 'USD',
            MQ: 'EUR',
            MR: 'MRO',
            MS: 'XCD',
            MT: 'MTL',
            MU: 'MUR',
            MV: 'MVR',
            MW: 'MWK',
            MX: 'MXN',
            MY: 'MYR',
            MZ: 'MZN',
            NA: 'NAD',
            NC: 'XPF',
            NE: 'XOF',
            NF: 'AUD',
            NG: 'NGN',
            NI: 'NIO',
            NL: 'EUR',
            NO: 'NOK',
            NP: 'NPR',
            NR: 'AUD',
            NU: 'NZD',
            NZ: 'NZD',
            OM: 'OMR',
            PA: 'PAB',
            PE: 'PEN',
            PF: 'XPF',
            PG: 'PGK',
            PH: 'PHP',
            PK: 'PKR',
            PL: 'PLN',
            PM: 'EUR',
            PN: 'NZD',
            PR: 'USD',
            PS: 'JOD',
            PT: 'EUR',
            PW: 'USD',
            PY: 'PYG',
            QA: 'QAR',
            RE: 'EUR',
            RO: 'RON',
            RS: 'RSD',
            RU: 'RUB',
            RW: 'RWF',
            SA: 'SAR',
            SB: 'SBD',
            SC: 'SCR',
            SD: 'SDG',
            SE: 'SEK',
            SG: 'SGD',
            SH: 'GBP',
            SI: 'EUR',
            SJ: 'NOK',
            SK: 'SKK',
            SL: 'SLL',
            SM: 'EUR',
            SN: 'XOF',
            SO: 'SOS',
            SR: 'SRD',
            ST: 'STD',
            SV: 'SVC',
            SY: 'SYP',
            SZ: 'SZL',
            TC: 'USD',
            TD: 'XAF',
            TF: 'EUR',
            TG: 'XOF',
            TH: 'THB',
            TJ: 'TJS',
            TK: 'NZD',
            TM: 'TMT',
            TN: 'TND',
            TO: 'TOP',
            TP: 'IDR',
            TR: 'TRY',
            TT: 'TTD',
            TV: 'AUD',
            TW: 'TWD',
            TZ: 'TZS',
            UA: 'UAH',
            UG: 'UGX',
            UM: 'USD',
            US: 'USD',
            UY: 'UYU',
            UZ: 'UZS',
            VA: 'EUR',
            VC: 'XCD',
            VE: 'VEF',
            VG: 'USD',
            VI: 'USD',
            VN: 'VND',
            VU: 'VUV',
            WF: 'XPF',
            WS: 'EUR',
            YE: 'YER',
            YT: 'EUR',
            ZA: 'ZAR',
            ZM: 'ZMK',
            ZW: 'ZWD'
        }
    }


    // State values are ISO_3166-2 subdivision code, which is required by Stripe
    // https://en.wikipedia.org/wiki/ISO_3166-2
    // https://stripe.com/docs/api/orders_v2/create#create_order_v2-shipping_details-address-state
    function getCountryStatesMap() {
        return {
            // United States
            US: {
                AL: 'Alabama',
                AK: 'Alaska',
                AZ: 'Arizona',
                AR: 'Arkansas',
                CA: 'California',
                CO: 'Colorado',
                CT: 'Connecticut',
                DE: 'Delaware',
                FL: 'Florida',
                GA: 'Georgia',
                HI: 'Hawaii',
                ID: 'Idaho',
                IL: 'Illinois',
                IN: 'Indiana',
                IA: 'Iowa',
                KS: 'Kansas',
                KY: 'Kentucky',
                LA: 'Louisiana',
                ME: 'Maine',
                MD: 'Maryland',
                MA: 'Massachusetts',
                MI: 'Michigan',
                MN: 'Minnesota',
                MS: 'Mississippi',
                MO: 'Missouri',
                MT: 'Montana',
                NE: 'Nebraska',
                NV: 'Nevada',
                NH: 'New Hampshire',
                NJ: 'New Jersey',
                NM: 'New Mexico',
                NY: 'New York',
                NC: 'North Carolina',
                ND: 'North Dakota',
                OH: 'Ohio',
                OK: 'Oklahoma',
                OR: 'Oregon',
                PA: 'Pennsylvania',
                RI: 'Rhode Island',
                SC: 'South Carolina',
                SD: 'South Dakota',
                TN: 'Tennessee',
                TX: 'Texas',
                UT: 'Utah',
                VT: 'Vermont',
                VA: 'Virginia',
                WA: 'Washington',
                WV: 'West Virginia',
                WI: 'Wisconsin',
                WY: 'Wyoming'
            },
            // Canada
            CA: {
                AB: 'Alberta',
                BC: 'British Columbia',
                MB: 'Manitoba',
                NB: 'New Brunswick',
                NL: 'Newfoundland and Labrador',
                NT: 'Northwest Territories',
                NS: 'Nova Scotia',
                NU: 'Nunavut',
                ON: 'Ontario',
                PE: 'Prince Edward Island',
                QC: 'Quebec',
                SK: 'Saskatchewan',
                YT: 'Yukon'
            },
            // Australia
            AU: {
                ACT: 'Australian Capital Territory',
                NSW: 'New South Wales',
                NT: 'Northern Territory',
                QLD: 'Queensland',
                SA: 'South Australia',
                TAS: 'Tasmania',
                VIC: 'Victoria',
                WA: 'Western Australia'
            },
            // Brazil
            BR: {
                AC: 'Acre',
                AL: 'Alagoas',
                AP: 'Amapá',
                AM: 'Amazonas',
                BA: 'Bahia',
                CE: 'Ceará',
                DF: 'Distrito Federal',
                ES: 'Espírito Santo',
                GO: 'Goiás',
                MA: 'Maranhão',
                MT: 'Mato Grasso',
                MS: 'Mato Grosso do Sul',
                MG: 'Minas Gerais',
                PA: 'Pará',
                PB: 'Paraíba',
                PR: 'Paraná',
                PE: 'Pernambuco',
                PI: 'Piauí',
                RJ: 'Rio de Janeiro',
                RN: 'Rio Grande do Norte',
                RS: 'Rio Grande do Sul',
                RO: 'Rondônia',
                RR: 'Roraima',
                SC: 'Santa Catarina',
                SP: 'São Paulo',
                SE: 'Sergipe',
                TO: 'Tocantins'
            },
            // Mexico
            MX: {
                AGS: 'Aguascalientes',
                BC: 'Baja California',
                BCS: 'Baja California Sur',
                CAMP: 'Campeche',
                CHIS: 'Chiapas',
                CHIH: 'Chihuahua',
                COAH: 'Coahuila',
                COL: 'Colima',
                DF: 'Distrito Federal',
                DGO: 'Durango',
                GTO: 'Guanajuato',
                GRO: 'Guerrero',
                HGO: 'Hidalgo',
                JAL: 'Jalisco',
                EDM: 'México',
                MICH: 'Michoacán',
                MOR: 'Morelos',
                NAY: 'Nayarit',
                NL: 'Nuevo León',
                OAX: 'Oaxaca',
                PUE: 'Puebla',
                QRO: 'Querétaro',
                QROO: 'Quintana Roo',
                SLP: 'San Luis Potosi',
                SIN: 'Sinaloa',
                SON: 'Sonora',
                TAB: 'Tabasco',
                TAMPS: 'Tamaulipas',
                TLAX: 'Tlaxcala',
                VER: 'Veracruz',
                YUC: 'Yucatán',
                ZAC: 'Zacatecas'
            }
        }
    };

    return {
        getCountries,
        getCountryCodeToCurrencyCodeMap,
        getCountryStatesMap
    }
}
